-- Database export: SAFE_ZONE
-- Date: 2026-09-10 12:11:49
-- Generated by DBX

CREATE SEQUENCE IF NOT EXISTS "public"."bins_bin_id_seq"
  AS integer
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."bins" (
  "bin_id" serial NOT NULL,
  "priceathour" integer NOT NULL,
  "pos_x" integer NOT NULL,
  "pos_y" integer NOT NULL,
  "size" text NOT NULL,
  "status" text NOT NULL,
  PRIMARY KEY ("bin_id")
);

INSERT INTO "public"."bins" ("bin_id", "priceathour", "pos_x", "pos_y", "size", "status") VALUES (1, 100, 1, 1, 'small', 'false'), (2, 100, 2, 1, 'small', 'true'), (3, 100, 3, 1, 'small', 'true'), (4, 100, 4, 1, 'small', 'true'), (5, 100, 5, 1, 'small', 'true'), (6, 500, 1, 2, 'medium', 'true'), (7, 500, 2, 2, 'medium', 'true'), (8, 500, 3, 2, 'medium', 'false'), (9, 500, 4, 2, 'medium', 'true'), (10, 500, 5, 2, 'medium', 'true'), (11, 1000, 1, 3, 'large', 'true'), (12, 1000, 2, 3, 'large', 'true'), (13, 1000, 3, 3, 'large', 'true'), (14, 1000, 4, 3, 'large', 'true'), (15, 1000, 5, 3, 'large', 'false');

CREATE SEQUENCE IF NOT EXISTS "public"."users_id_seq"
  AS integer
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."users" (
  "id" serial NOT NULL,
  "login" text NOT NULL,
  "password" text NOT NULL,
  "status" text NOT NULL DEFAULT 'active'::text,
  "role" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "users_status_check" CHECK (status = ANY (ARRAY['active'::text, 'blocked'::text, 'deleted'::text]))
);
CREATE UNIQUE INDEX "users_login_key" ON "public"."users" USING btree ("login");

INSERT INTO "public"."users" ("id", "login", "password", "status", "role") VALUES (1, 'admin', '1234', 'active', 'admin'), (2, 'TestUser', '1234', 'active', 'client');

CREATE SEQUENCE IF NOT EXISTS "public"."payments_order_id_seq"
  AS integer
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 2147483647
  CACHE 1
  NO CYCLE;

CREATE TABLE "public"."payments" (
  "order_id" serial NOT NULL,
  "bin_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "priceathour" integer NOT NULL,
  "status" text NOT NULL DEFAULT 'pending'::text,
  "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "update_at" timestamp with time zone,
  "end_rent_date" timestamp with time zone NOT NULL,
  "rentTime" integer,
  PRIMARY KEY ("order_id"),
  CONSTRAINT "fk_payments_bin" FOREIGN KEY ("bin_id") REFERENCES "bins"("bin_id"),
  CONSTRAINT "fk_payments_user" FOREIGN KEY ("user_id") REFERENCES "users"("id")
);

INSERT INTO "public"."payments" ("order_id", "bin_id", "user_id", "priceathour", "status", "created_at", "update_at", "end_rent_date", "rentTime") VALUES (1, 1, 2, 100, 'PAID', '2026-09-10 00:00:00+03:00', NULL, '2026-10-10 00:00:00+03:00', 30), (2, 8, 2, 500, 'PAID', '2026-09-10 00:00:00+03:00', NULL, '2026-09-12 00:00:00+03:00', 2);

ALTER SEQUENCE "public"."bins_bin_id_seq" OWNED BY "public"."bins"."bin_id";

ALTER SEQUENCE "public"."payments_order_id_seq" OWNED BY "public"."payments"."order_id";

ALTER SEQUENCE "public"."users_id_seq" OWNED BY "public"."users"."id";

SELECT setval('"public"."users_id_seq"', GREATEST(COALESCE(MAX("id"), 2), 2), true) FROM "public"."users";

