foreground = white
background = black
com.googlecode.lanterna.gui2.Button.foreground = white
com.googlecode.lanterna.gui2.Button.background = black
com.googlecode.lanterna.gui2.Button.foreground[ACTIVE] = black
com.googlecode.lanterna.gui2.Button.background[ACTIVE] = cyan
com.googlecode.lanterna.gui2.Button.foreground[SELECTED] = black
com.googlecode.lanterna.gui2.Button.background[SELECTED] = cyan_bright
com.googlecode.lanterna.gui2.Button.foreground[PRESELECTED] = white
com.googlecode.lanterna.gui2.Button.background[PRESELECTED] = blue

com.googlecode.lanterna.gui2.TextBox.foreground = white
com.googlecode.lanterna.gui2.TextBox.background = black
com.googlecode.lanterna.gui2.TextBox.foreground[ACTIVE] = black
com.googlecode.lanterna.gui2.TextBox.background[ACTIVE] = white
com.googlecode.lanterna.gui2.TextBox.foreground[PRESELECTED] = white
com.googlecode.lanterna.gui2.TextBox.background[PRESELECTED] = blue

com.googlecode.lanterna.gui2.Label.foreground = white
com.googlecode.lanterna.gui2.Label.background = black

com.googlecode.lanterna.gui2.Panel.foreground = white
com.googlecode.lanterna.gui2.Panel.background = black

com.googlecode.lanterna.gui2.table.Table.foreground = white
com.googlecode.lanterna.gui2.table.Table.background = black
com.googlecode.lanterna.gui2.table.Table.foreground[ACTIVE] = black
com.googlecode.lanterna.gui2.table.Table.background[ACTIVE] = cyan_bright
com.googlecode.lanterna.gui2.table.Table.foreground[SELECTED] = black
com.googlecode.lanterna.gui2.table.Table.background[SELECTED] = cyan
